FROM debian:latest

RUN apt-get update && apt-get install -y \
    sudo \
    curl \
    git \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash f3ar13ss && \
    echo "f3ar13ss ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER f3ar13ss
WORKDIR /home/f3ar13ss/devenv

COPY --chown=f3ar13ss:f3ar13ss . .

CMD ["./devenv.sh", "--ci"]
