FROM opensuse/leap:latest

RUN zypper update -y && zypper in -y \
    sudo \
    curl \
    git \
    tar \
    gzip

RUN useradd -m -s /bin/bash spider && \
    echo "spider ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER spider
WORKDIR /home/spider

COPY . /app
WORKDIR /app

CMD ["bash"]
